-- ============================================
-- MIGRATION: Volontaires d'événement + historique des envois de mail
-- ============================================

-- Liste des volontaires, scopée par événement (ajout manuel ou import Excel)
CREATE TABLE IF NOT EXISTS public.event_volunteers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES public.events(id) ON DELETE CASCADE,
    fullname TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.event_volunteers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated read for event_volunteers"
ON public.event_volunteers FOR SELECT TO authenticated USING (true);

CREATE POLICY "Allow authenticated insert for event_volunteers"
ON public.event_volunteers FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Allow authenticated update for event_volunteers"
ON public.event_volunteers FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Allow authenticated delete for event_volunteers"
ON public.event_volunteers FOR DELETE TO authenticated USING (true);

-- Historique des envois de mail "libres" (volontaires ou participants) par événement,
-- séparé de sent_newsletters pour ne pas mélanger les statistiques de la newsletter générale.
CREATE TABLE IF NOT EXISTS public.sent_event_emails (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES public.events(id) ON DELETE CASCADE,
    target_group TEXT NOT NULL, -- 'volunteers' | 'participants'
    subject TEXT NOT NULL,
    recipients_count INTEGER NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.sent_event_emails ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated read for sent_event_emails"
ON public.sent_event_emails FOR SELECT TO authenticated USING (true);

CREATE POLICY "Allow authenticated insert for sent_event_emails"
ON public.sent_event_emails FOR INSERT TO authenticated WITH CHECK (true);
