-- ============================================
-- MIGRATION: AUDIT V2 - UI & FEATURES
-- ============================================

-- 1. Updates for form_submissions (Applications)
-- Supprimer les anciennes contraintes pour éviter les conflits
ALTER TABLE public.form_submissions DROP CONSTRAINT IF EXISTS check_status;
ALTER TABLE public.form_submissions DROP CONSTRAINT IF EXISTS form_submissions_status_check;

-- S'assurer que la colonne existe
ALTER TABLE public.form_submissions ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'en_attente';

-- Nettoyage agressif des données (enlève les espaces et les valeurs invalides)
UPDATE public.form_submissions 
SET status = 'en_attente' 
WHERE status IS NULL 
   OR TRIM(status) = '' 
   OR TRIM(status) NOT IN ('en_attente', 'entretien', 'accepte', 'refuse');

-- Mise à jour propre (sans espaces)
UPDATE public.form_submissions SET status = TRIM(status);

-- Ré-appliquer la contrainte propre
ALTER TABLE public.form_submissions ADD CONSTRAINT check_status CHECK (status IN ('en_attente', 'entretien', 'accepte', 'refuse'));

-- 2. Updates for documents table
ALTER TABLE public.documents 
ADD COLUMN IF NOT EXISTS file_format TEXT,
ADD COLUMN IF NOT EXISTS file_type TEXT;

-- 3. Discussion Messages Table
CREATE TABLE IF NOT EXISTS public.discussion_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content TEXT NOT NULL,
  user_id UUID NOT NULL REFERENCES public.user_profiles(id) ON DELETE CASCADE,
  recipient_id UUID REFERENCES public.user_profiles(id) ON DELETE CASCADE,
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Ensure columns exist if table was created previously without them
ALTER TABLE public.discussion_messages ADD COLUMN IF NOT EXISTS is_read BOOLEAN DEFAULT FALSE;
ALTER TABLE public.discussion_messages ADD COLUMN IF NOT EXISTS recipient_id UUID REFERENCES public.user_profiles(id) ON DELETE CASCADE;

-- Ensure recipient_id exists and references user_profiles if the table was created previously
ALTER TABLE public.discussion_messages DROP CONSTRAINT IF EXISTS discussion_messages_user_id_fkey;
ALTER TABLE public.discussion_messages ADD CONSTRAINT discussion_messages_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id) ON DELETE CASCADE;

ALTER TABLE public.discussion_messages DROP CONSTRAINT IF EXISTS discussion_messages_recipient_id_fkey;
ALTER TABLE public.discussion_messages ADD CONSTRAINT discussion_messages_recipient_id_fkey FOREIGN KEY (recipient_id) REFERENCES public.user_profiles(id) ON DELETE CASCADE;

-- Enable RLS
ALTER TABLE public.discussion_messages ENABLE ROW LEVEL SECURITY;

-- Policies for private messages
DROP POLICY IF EXISTS "Users can only see their own private messages" ON public.discussion_messages;
CREATE POLICY "Users can only see their own private messages" ON public.discussion_messages
    FOR SELECT USING (
        auth.role() = 'authenticated' 
        AND (recipient_id IS NULL OR user_id = auth.uid() OR recipient_id = auth.uid())
    );

DROP POLICY IF EXISTS "Users can only insert their own messages" ON public.discussion_messages;
CREATE POLICY "Users can only insert their own messages" ON public.discussion_messages
    FOR INSERT WITH CHECK (auth.role() = 'authenticated' AND user_id = auth.uid());

-- 4. Analytics: Site Visits Table
CREATE TABLE IF NOT EXISTS public.site_visits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visit_date DATE DEFAULT CURRENT_DATE UNIQUE,
    count INTEGER DEFAULT 1
);

-- Enable RLS for analytics
ALTER TABLE public.site_visits ENABLE ROW LEVEL SECURITY;

-- Policy: Allow any authenticated user to upsert (increment) visits
DROP POLICY IF EXISTS "Allow visit increments" ON public.site_visits;
CREATE POLICY "Allow visit increments" ON public.site_visits
    FOR ALL USING (true) WITH CHECK (true);

-- RPC for incrementing visits (fixes 404)
CREATE OR REPLACE FUNCTION public.increment_visit(d DATE)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  INSERT INTO public.site_visits (visit_date, count)
  VALUES (d, 1)
  ON CONFLICT (visit_date)
  DO UPDATE SET count = site_visits.count + 1;
END;
$$;

-- 5. Robust User Profile Sync & Missing Columns
-- Fixes missing avatar_url (400 error)
ALTER TABLE public.user_profiles ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE public.user_profiles ADD COLUMN IF NOT EXISTS avatar_url TEXT;

-- Synchronize users
INSERT INTO public.user_profiles (id, email, full_name, role)
SELECT 
    id, 
    email, 
    COALESCE(raw_user_meta_data->>'full_name', email),
    COALESCE(raw_user_meta_data->>'role', 'membre')
FROM auth.users
ON CONFLICT (id) DO UPDATE SET
    email = EXCLUDED.email,
    full_name = COALESCE(user_profiles.full_name, EXCLUDED.full_name);

-- Ensure RLS allows all authenticated users to see each other
DROP POLICY IF EXISTS "Allow authenticated read access" ON public.user_profiles;
DROP POLICY IF EXISTS "Allow authenticated read visibility for all profiles" ON public.user_profiles;
CREATE POLICY "Allow authenticated read visibility for all profiles" 
ON public.user_profiles FOR SELECT TO authenticated USING (true);

-- Commentary: Audit V2 Phase 3.1 - Analytics RPC & Missing Columns Fix.
