-- ============================================
-- MIGRATION: Newsletter Metrics
-- ============================================

-- Create table to track sent newsletters
CREATE TABLE IF NOT EXISTS public.sent_newsletters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject TEXT NOT NULL,
    recipients_count INTEGER NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.sent_newsletters ENABLE ROW LEVEL SECURITY;

-- Policy: Allow authenticated users to read stats
CREATE POLICY "Allow authenticated read for sent_newsletters" 
ON public.sent_newsletters FOR SELECT TO authenticated USING (true);

-- Policy: Allow authenticated users to insert stats
CREATE POLICY "Allow authenticated insert for sent_newsletters" 
ON public.sent_newsletters FOR INSERT TO authenticated WITH CHECK (true);
