-- ============================================
-- MIGRATION: PARTNERS, DONATIONS & EVENTS
-- ============================================

-- 1. Update form_submissions to include type
ALTER TABLE public.form_submissions ADD COLUMN IF NOT EXISTS type TEXT DEFAULT 'membership' CHECK (type IN ('membership', 'partnership'));

-- 2. Create donations table
CREATE TABLE IF NOT EXISTS public.donations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fullname TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT,
    donation_type TEXT NOT NULL CHECK (donation_type IN ('financier', 'materiel', 'autre')),
    amount TEXT, 
    description TEXT,
    status TEXT DEFAULT 'en_attente' CHECK (status IN ('en_attente', 'valide', 'annule')),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for donations
ALTER TABLE public.donations ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public to insert donations" ON public.donations;
CREATE POLICY "Allow public to insert donations" 
ON public.donations FOR INSERT TO public WITH CHECK (true);

DROP POLICY IF EXISTS "Allow authenticated users to read donations" ON public.donations;
CREATE POLICY "Allow authenticated users to read donations" 
ON public.donations FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Allow authenticated users to update donations" ON public.donations;
CREATE POLICY "Allow authenticated users to update donations" 
ON public.donations FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

-- 3. Create events table
CREATE TABLE IF NOT EXISTS public.events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    event_date TIMESTAMPTZ NOT NULL,
    location TEXT,
    image_url TEXT,
    max_slots INTEGER,
    status TEXT DEFAULT 'published' CHECK (status IN ('draft', 'published', 'cancelled')),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for events
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read access to events" ON public.events;
CREATE POLICY "Allow public read access to events" 
ON public.events FOR SELECT TO public USING (true);

DROP POLICY IF EXISTS "Allow authenticated users full access to events" ON public.events;
CREATE POLICY "Allow authenticated users full access to events" 
ON public.events FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- 4. Create event_registrations table
CREATE TABLE IF NOT EXISTS public.event_registrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT REFERENCES public.events(id) ON DELETE CASCADE,
    fullname TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for event_registrations
ALTER TABLE public.event_registrations ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public to insert registrations" ON public.event_registrations;
CREATE POLICY "Allow public to insert registrations" 
ON public.event_registrations FOR INSERT TO public WITH CHECK (true);

DROP POLICY IF EXISTS "Allow authenticated users to read registrations" ON public.event_registrations;
CREATE POLICY "Allow authenticated users to read registrations" 
ON public.event_registrations FOR SELECT TO authenticated USING (true);

-- 5. Trigger for updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

DROP TRIGGER IF EXISTS update_donations_updated_at ON public.donations;
CREATE TRIGGER update_donations_updated_at BEFORE UPDATE ON public.donations FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

DROP TRIGGER IF EXISTS update_events_updated_at ON public.events;
CREATE TRIGGER update_events_updated_at BEFORE UPDATE ON public.events FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
