-- 1. Add form_fields to events
ALTER TABLE public.events ADD COLUMN IF NOT EXISTS form_fields JSONB DEFAULT '[]'::jsonb;

-- 1b. Add feedback_config to events (feedback form fields + options)
ALTER TABLE public.events ADD COLUMN IF NOT EXISTS feedback_config JSONB DEFAULT '{"show_stars": true, "fields": []}'::jsonb;

-- 2. Add custom_data to event_registrations
ALTER TABLE public.event_registrations ADD COLUMN IF NOT EXISTS custom_data JSONB DEFAULT '{}'::jsonb;

-- 3. Create event_feedbacks table
CREATE TABLE IF NOT EXISTS public.event_feedbacks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT REFERENCES public.events(id) ON DELETE CASCADE,
    participant_name TEXT,
    rating INTEGER CHECK (rating >= 1 AND rating <= 5),
    comment TEXT,
    custom_answers JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add custom_answers column if table already existed
ALTER TABLE public.event_feedbacks ADD COLUMN IF NOT EXISTS custom_answers JSONB DEFAULT '{}'::jsonb;

-- Enable RLS for event_feedbacks
ALTER TABLE public.event_feedbacks ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public to insert feedbacks" ON public.event_feedbacks;
CREATE POLICY "Allow public to insert feedbacks" 
ON public.event_feedbacks FOR INSERT TO public WITH CHECK (true);

DROP POLICY IF EXISTS "Allow authenticated users to read feedbacks" ON public.event_feedbacks;
CREATE POLICY "Allow authenticated users to read feedbacks" 
ON public.event_feedbacks FOR SELECT TO authenticated USING (true);
