
-- Add custom form configuration to events
ALTER TABLE public.events ADD COLUMN IF NOT EXISTS form_fields JSONB DEFAULT '[]'::jsonb;

-- Add custom data storage to event registrations
ALTER TABLE public.event_registrations ADD COLUMN IF NOT EXISTS custom_data JSONB DEFAULT '{}'::jsonb;

-- Create Event Feedbacks Table
CREATE TABLE IF NOT EXISTS public.event_feedbacks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT REFERENCES public.events(id) ON DELETE CASCADE,
    participant_name TEXT NOT NULL,
    rating INTEGER CHECK (rating >= 1 AND rating <= 5),
    comment TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS for event_feedbacks
ALTER TABLE public.event_feedbacks ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public to insert feedbacks" ON public.event_feedbacks;
CREATE POLICY "Allow public to insert feedbacks" 
ON public.event_feedbacks FOR INSERT TO public WITH CHECK (true);

DROP POLICY IF EXISTS "Allow authenticated users to read feedbacks" ON public.event_feedbacks;
CREATE POLICY "Allow authenticated users to read feedbacks" 
ON public.event_feedbacks FOR SELECT TO authenticated USING (true);
