-- ============================================================
-- 041 — ANTI BRUTE-FORCE SUR /admin/login
-- ============================================================
-- Avant : AdminLogin.tsx appelait signInWithPassword() en direct,
-- aucune limite de tentatives. Un script pouvait tester des
-- milliers de mots de passe sans être ralenti.
--
-- Ce fichier crée la table qui enregistre chaque tentative
-- (email, ip, succès/échec). Le verrouillage lui-même est calculé
-- par l'edge function `admin-login` (service role), qui est le
-- SEUL point d'entrée pour se connecter désormais.
--
-- RLS activé, AUCUNE policy anon/authenticated : ni lecture ni
-- écriture depuis le navigateur, même connecté. Seul le service
-- role (edge function) y accède, ce qui empêche un attaquant de
-- lire quels emails ont déjà été essayés, ou de nettoyer ses
-- propres tentatives pour contourner le verrou.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.login_attempts (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email      text NOT NULL,
  ip         text,
  success    boolean NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_login_attempts_email_time
  ON public.login_attempts (lower(email), created_at DESC);
CREATE INDEX IF NOT EXISTS idx_login_attempts_ip_time
  ON public.login_attempts (ip, created_at DESC);

ALTER TABLE public.login_attempts ENABLE ROW LEVEL SECURITY;
-- Aucune policy : verrouillé pour anon ET authenticated. Seul le
-- service role (qui contourne RLS) peut lire/écrire.

-- Purge : pas besoin de garder ça indéfiniment. À relancer de temps
-- en temps (ou via pg_cron si dispo) :
-- DELETE FROM public.login_attempts WHERE created_at < now() - interval '30 days';
