-- ============================================================
-- 042 — RATE LIMITING SUR LES FORMULAIRES PUBLICS
-- ============================================================
-- Avant : newsletter, adhésion, partenariat, don, inscription event
-- n'avaient AUCUNE limite de fréquence. Turnstile est en mode
-- consultatif (cf. 038/verify-submission), donc rien ne bloquait
-- un script envoyant des centaines de soumissions avec des emails
-- syntaxiquement valides.
--
-- Table de journalisation utilisée par l'edge function
-- verify-submission pour compter les tentatives récentes par IP et
-- par email, tous formulaires confondus. Même principe que
-- login_attempts (041) : RLS activée, AUCUNE policy -> illisible et
-- non falsifiable depuis le navigateur, accès service role
-- uniquement.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.submission_log (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind       text NOT NULL,           -- 'newsletter' | 'membership' | 'partnership' | 'donation' | 'event_registration' | 'unknown'
  email      text,
  ip         text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_submission_log_ip_time
  ON public.submission_log (ip, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_submission_log_email_time
  ON public.submission_log (lower(email), created_at DESC);

ALTER TABLE public.submission_log ENABLE ROW LEVEL SECURITY;
-- Aucune policy : verrouillé pour anon ET authenticated.

-- Purge périodique (à relancer de temps en temps) :
-- DELETE FROM public.submission_log WHERE created_at < now() - interval '30 days';
